ARG BASE_IMAGE=ubi8
ARG RTEVAL_RPM_URL

FROM ${BASE_IMAGE}

USER root
COPY rteval/cmd.sh /root
COPY common-libs /root/common-libs

RUN if [[ -z "${RTEVAL_RPM_URL}" ]]; then \
		echo "Error: Please provide the URL for the rteval RPM"; \
		exit 1; \
else \
		echo "rteval RPM URL is \'${RTEVAL_RPM_URL}\'"; \
fi

RUN yum -y install ${RTEVAL_RPM_URL} \
    && yum clean all && rm -rf /var/cache/yum \
    && curl -L -o /root/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64 \
    && chmod 777 /root/dumb-init \
    && chmod 777 /root/cmd.sh
WORKDIR /root
ENTRYPOINT ["/root/dumb-init", "--"]
CMD ["/root/cmd.sh"]
